
config rtp2httpd
	option respawn '1'
	option disabled '0'
	option use_config_file '0'
	option zerocopy_on_send '0'
	option port '5140'
	option verbose '1'
	option upstream_interface 'eth1'
	option workers '1'
	option maxclients '10'
	option buffer_pool_max_size '65536'
	option external_m3u 'file:///www/iptv/tv.m3u'
	option external_m3u_update_interval '0'
	option mcast_rejoin_interval '0'
	option fcc_listen_port_range '40000-40100'

